### ISSUE TITLE
LimeSDR-Mini firmware

### ISSUE THREAD

**Issue by cederom** [myriadrf/LimeSDR-Mini#2]
Hello world :-)

We are porting LimeSuite to FreeBSD. Working on LimeSDR-Mini. There seems to be a set of issues with LimeSDR both USB and radio part. Where can we find source code repository and support for those issues?

Identified issues so far:
1. LibUSB open / reset impossible on FreeBSD when working as user (only root can reset hardware USB ports).
2. Hardware Self-Test fail with LimeQuickTest.
3. MCU error 3 / Tx Calibration: MCU error 3 (SXR tune failed).
4. MCU error 5 / Tx Calibration: MCU error 5 (Loopback signal weak: not connected/insufficient gain?).

The work in progress is documented here:
https://github.com/myriadrf/LimeSuite/wiki/LimeSDR-on-FreeBSD

**Comment by 9600** [comment]
Support for LimeSDR hardware is provided by Lime Suite, hence the source code in [this repository](https://github.com/myriadrf/LimeSuite).

Please run LimeQuickTest on a Linux host, with the latest version of Lime Suite installed, while ensuring that nothing is connected to any of the RF ports and that the board is cold (pass/fail criteria are not valid when a board has been running for some time and is warm). If you still get failures, it could be hardware related. Otherwise I would imagine it to be related to the different host O/S and porting.

Note that any general support questions should be directed to the [MyriadRF forums](https://discourse.myriadrf.org/).

**Comment by cederom** [comment]
Hello @9600 :-) I am porting the LimeSuite to FreeBSD, some problems seems firmware related (i.e. device reset vs port reset, also the self-test fails). They occur on various other devices and operating systems. Where can we find firmware source code for LimeSDR-Mini? Is it Open-Source?

**Comment by cederom** [comment]
Looks like sources are available here:
1. GateWare for FPGA: https://github.com/myriadrf/LimeSDR-Mini_GW
2. MCU Firmware (LMS7002M): https://github.com/myriadrf/LimeSuite/tree/master/mcu_program

Thank you @daniestevez :-)
